### ISSUE TITLE
Output is not finished in error

### ISSUE THREAD

**Issue by Kanazawanaoaki** [jsk-ros-pkg/euslime#8]
**Describe the bug**
Full output is not shown before error message

**Log \*inferior-lisp\***
```
[INFO - bridge:L383] eval: (mapcar #'foo hoge)

[DEBUG - server:L46] output: ("class_file" . "/project_data/rcup_20220218_pick_nopb/models/class.yaml")
("control_joints" (("name" . "r_shoulder_pan_joint") ("type" . "revolute")) (("name" . "r_shoulder_lift_joint") ("type" . "revolute")) (("name" . "r_upper_arm_roll_joint") ("type" . "revolute")) (("name" . "r_elbow_flex_joint") ("type" . "revolute")) (("cl
[DEBUG - bridge:L226] Socket Response: 000005
[DEBUG - bridge:L226] Socket Response: error
[DEBUG - bridge:L249] Waiting for socket data...
[DEBUG - bridge:L226] Socket Response: 00001a
[DEBUG - bridge:L256] Socket Request Type: error
[DEBUG - bridge:L226] Socket Response: "list expected in (cdr a)"
[DEBUG - bridge:L226] Socket Response: 000005
[DEBUG - bridge:L226] Socket Response: abort
[DEBUG - bridge:L116] accumulating output: amp" . t) ("name" . "r_forearm_roll_joint") ("type" . "continuous")) (("name" . "r_wrist_flex_joint") ("type" . "revolute")) (("clamp" . t) ("name" . "r_wrist_roll_joint") ("type" . "continuous")))
(("name" . "r_shoulder_pan_joint") ("type" . "revolute"))
("type" . "revolute")
(("name" . "r_shoulder_lift_joint") ("type" . "revolute"))
("type" . "revolute")
(("name" . "r_upper_arm_roll_joint") ("type" . "revolute"))
("type" . "revolute")
(("name" . "r_elbow_flex_joint") ("type" . "revolute"))
("type" . "revolute")
(("clamp" . t) ("name" . "r_forearm_roll_joint") ("type" . "continuous"))
("name" . "r_forearm_roll_joint")
("type" . "continuous")
(("name" . "r_wrist_flex_joint") ("type" . "revolute"))
("type" . "revolute")
(("clamp" . t) ("name" . "r_wrist_roll_joint") ("type" . "continuous"))
("name" . "r_wrist_roll_joint")
("type" . "continuous")
("dim_list" 6 7)
6

[DEBUG - bridge:L249] Waiting for socket data...
[DEBUG - bridge:L121] repl output finished
[DEBUG - bridge:L226] Socket Response: 000003
[DEBUG - bridge:L226] Socket Response: nil
[DEBUG - bridge:L316] Ignoring: [abort] nil
[INFO - bridge:L324] exec: (slime:print-callstack 14)
[DEBUG - bridge:L116] accumulating output: Call Stack (max depth: 14):
  0: at (slime:print-callstack 14)
  1: at slime:slime-error
  2: at slime:slime-error
  3: at (cdr a)
  4: at (consp (cdr a))
  5: at (if (consp (cdr a)) (mapcar #'foo (cdr a)) (cons (intern (string-upcase (car a))) (cdr a)))
  6: at (mapcar #'foo (cdr a))
  7: at (mapcar #'foo (cdr a))
  8: at (if (consp (cdr a)) (mapcar #'foo (cdr a)) (cons (intern (string-upcase (car a))) (cdr a)))
  9: at (mapcar #'foo hoge)
  10: at (mapcar #'foo hoge)
  11: at (slime:slimetop)
  12: at (slime:slimetop)
  13: at #<compiled-code #X56468267ff50>

[DEBUG - bridge:L121] repl output finished
[DEBUG - bridge:L226] Socket Response: 000005
[DEBUG - bridge:L226] Socket Response: error
[DEBUG - bridge:L249] Waiting for socket data...
[DEBUG - bridge:L226] Socket Response: 00002f
[DEBUG - bridge:L256] Socket Request Type: error
[DEBUG - bridge:L226] Socket Response: "print-callstack in (slime:print-callstack 14)"
[DEBUG - bridge:L272] Waiting for repl output...
[DEBUG - bridge:L121] repl output finished
[ERROR - handler:L274] Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/euslime/handler.py", line 239, in swank_eval
    for val in self.euslisp.eval(sexp):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/euslime/bridge.py", line 389, in eval
    for r in self.get_socket_result(connection, wait=True):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/euslime/bridge.py", line 290, in get_socket_result
    gen = self.get_socket_response(connection)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/euslime/bridge.py", line 280, in get_socket_response
    raise EuslispError(msg, stack)
EuslispError: List expected in (cdr a)
```

**Comment by Kanazawanaoaki** [comment]
```lisp
(defun foo (a)
            (print a)
            (unix:usleep 100000)
            (if (consp (cdr a))
                (mapcar #'foo (cdr a))
                (cons (intern (string-upcase (car a))) (cdr a))))

(setq hoge (ros::get-param "/yaml_confg_eus"))
irteusgl> (mapcar #'foo hoge)
```

```
## ibm config
image_vae: False
image_channel: 3
image_width: 128
image_height: 128
image_units: [256, 6]
image_model_file: "/project_data/sample_rcup_reach_nopb/models/image_model.npz"

sensor_topic_list: ['image_latent', 'joint_angle']
mf_slop: 0.15
mf_queue_size: 30

dim_list: [6, 7]
n_pb: 0
n_init: 2
units: [100, 30, 10]
hz: 5

model_dir: "informatized_pr2_imitation"
model_file: "/project_data/sample_rcup_reach_nopb/models/model.npz"
mask_file: "/project_data/sample_rcup_reach_nopb/models/mask.yaml"
class_file: "/project_data/sample_rcup_reach_nopb/models/class.yaml"

## imitation pr2 config
control_joints: [{name: r_shoulder_pan_joint, type: revolute},
                 {name: r_shoulder_lift_joint, type: revolute},
                 {name: r_upper_arm_roll_joint, type: revolute},
                 {name: r_elbow_flex_joint, type: revolute},
                 {name: r_forearm_roll_joint, type: continuous, clamp: True},
                 {name: r_wrist_flex_joint, type: revolute},
                 {name: r_wrist_roll_joint, type: continuous, clamp: True}]
image_crop_offset_x: 180
image_crop_offset_y: 150
image_crop_width: 280
image_crop_height: 250
```

**Comment by Affonso-Gui** [comment]
I was able to recreate the problem by trying the last line a few times. Will check as soon as I can.
